// import { version } from "process";
// import { engineTypes } from "~/custom-server/database/engineTypes";
// import { transmissions } from "~/custom-server/database/transmissions";
// import { ICar, IProduct } from "~/interfaces/product";
// import { IUser } from "~/interfaces/user";

// const user: IUser = {
//     firstName: "Affan",
//     lastName: "Ashraf",
//     phone: "+923214371392",
//     email: "affanashraf313@gmail.com",
//     avatar: "",
// };

// const type = {
//     slug: "default",
//     name: "Default",
//     attributeGroups: [
//         {
//             name: "General",
//             slug: "general",
//             attributes: [
//                 "speed",
//                 "power-source",
//                 "battery-cell-type",
//                 "voltage",
//                 "battery-capacity",
//                 "material",
//                 "engine-type",
//             ],
//         },
//         {
//             name: "Dimensions",
//             slug: "dimensions",
//             attributes: ["length", "width", "height"],
//         },
//     ],
// };

// const _t = {
//     CVT: {
//         slug: "cvt",
//         name: "Continuously Variable Transmission (CVT)",
//     },
//     DCT: {
//         slug: "dct",
//         name: "Dual Clutch Transmission (DCT)",
//     },
//     AMT: {
//         slug: "amt",
//         name: "Automatic Manual Transmission (AMT)",
//     },
// };

// const _e = {
//     PETROL: {
//         slug: "petrol",
//         name: "Petrol",
//     },
//     DIESEL: {
//         slug: "diesel",
//         name: "Diesel",
//     },
//     HYBRID: {
//         slug: "hybrid",
//         name: "Hybrid",
//     },
//     CNG: {
//         slug: "cng",
//         name: "CNG",
//     },
//     LPG: {
//         slug: "lpg",
//         name: "LPG",
//     },
// };

// export const car: ICar = {
//     // make: "Honda",
//     model: "Civic",
//     version: "1.8 i-VTEC",
//     transaction: {
//         transactionType: "Cash",
//         flatPrice: 3200000,
//     },
//     transmission: _t.CVT,
//     year: new Date(Date.parse("11/03/2021")),
//     mileage: 0,
//     assembly: "Local",
//     bodyType: bodyTypes[0],
//     engine: _e.PETROL,
//     colors: [""],
//     engineCapacity: 1800,
//     postedDate: new Date(Date.parse("11/03/2021")),
//     province: "Punjab",
//     city: "Lahore",
//     registrationCity: "Lahore",
//     user: user,
// };

// export const carPosts: IProduct[] = [
//     {
//         id: 1,
//         slug: "honda-civic-1.8l-i-vtec",
//         name: "Honda Civic 1.8L i-VTEC",
//         excerpt: "",
//         description: "",
//         price: 3200000,
//         compareAtPrice: 3100000,
//         tags: ["Honda"],
//         colors: ["red"],
//         model: "Civic",
//         version: "1.8 i-VTEC",
//         transaction: {
//             transactionType: "Cash",
//             flatPrice: 3200000,
//         },
//         transmission: _t.CVT,
//         year: new Date(Date.parse("11/03/2021")),
//         mileage: 0,
//         assembly: "Local",
//         bodyType: bodyTypes[0],
//         images: ["honda-civic-1.8l-i-vtec.png"],
//         engine: _e.PETROL,
//         engineCapacity: 1800,
//         postedDate: new Date(Date.parse("11/03/2021")),
//         province: "Punjab",
//         city: "Lahore",
//         registrationCity: "Lahore",
//         user: user,

//         partNumber: "2323",
//         stock: "in-stock",
//         compatibility: "all",
//         type,
//         attributes: [],
//         options: [],

//         rating: 5,

//         badges: ["New"],
//     },
//     {
//         id: 2,
//         slug: "honda-civic-1.8l-i-vtec",
//         name: "Honda Civic 1.8L i-VTEC",
//         excerpt: "",
//         description: "",
//         model: "Civic",
//         version: "1.8 i-VTEC",
//         price: 3200000,
//         compareAtPrice: 3100000,
//         transaction: {
//             transactionType: "Cash",
//             flatPrice: 3200000,
//         },
//         tags: ["Honda"],
//         colors: ["red"],
//         transmission: _t.CVT,

//         partNumber: "2323",
//         stock: "in-stock",
//         compatibility: "all",
//         type,
//         attributes: [],
//         options: [],

//         year: new Date(Date.parse("11/03/2021")),
//         mileage: 0,
//         assembly: "Local",
//         bodyType: bodyTypes[0],
//         images: ["honda-civic-1.8l-i-vtec.png"],
//         engine: _e.PETROL,
//         engineCapacity: 1800,
//         postedDate: new Date(Date.parse("11/03/2021")),
//         province: "Punjab",
//         city: "Lahore",
//         registrationCity: "Lahore",
//         rating: 5,
//         user: user,
//         badges: ["New"],
//     },
//     {
//         id: 3,
//         slug: "honda-civic-1.8l-i-vtec",
//         name: "Honda Civic 1.8L i-VTEC",
//         excerpt: "",
//         description: "",
//         model: "Civic",
//         version: "1.8 i-VTEC",
//         price: 3200000,
//         compareAtPrice: 3100000,
//         transaction: {
//             transactionType: "Cash",
//             flatPrice: 3200000,
//         },
//         tags: ["Honda"],
//         colors: ["red"],
//         transmission: _t.CVT,

//         partNumber: "2323",
//         stock: "in-stock",
//         compatibility: "all",
//         type,
//         attributes: [],
//         options: [],

//         year: new Date(Date.parse("11/03/2021")),
//         mileage: 0,
//         assembly: "Local",
//         bodyType: bodyTypes[0],
//         images: ["honda-civic-1.8l-i-vtec.png"],
//         engine: _e.PETROL,
//         engineCapacity: 1800,
//         postedDate: new Date(Date.parse("11/03/2021")),
//         province: "Punjab",
//         city: "Lahore",
//         registrationCity: "Lahore",
//         rating: 5,
//         user: user,
//         badges: ["New"],
//     },
//     {
//         id: 4,
//         slug: "honda-civic-1.8l-i-vtec",
//         name: "Honda Civic 1.8L i-VTEC",
//         excerpt: "",
//         description: "",
//         make: "Honda",
//         model: "Civic",
//         version: "1.8 i-VTEC",
//         price: 3200000,
//         compareAtPrice: 3100000,
//         transaction: {
//             transactionType: "Cash",
//             flatPrice: 3200000,
//         },
//         tags: ["Honda"],
//         colors: ["red"],
//         transmission: _t.CVT,

//         partNumber: "2323",
//         stock: "in-stock",
//         compatibility: "all",
//         type,
//         attributes: [],
//         options: [],

//         year: new Date(Date.parse("11/03/2021")),
//         mileage: 0,
//         assembly: "Local",
//         bodyType: bodyTypes[0],
//         images: ["honda-civic-1.8l-i-vtec.png"],
//         engine: _e.PETROL,
//         engineCapacity: 1800,
//         postedDate: new Date(Date.parse("11/03/2021")),
//         province: "Punjab",
//         city: "Lahore",
//         registrationCity: "Lahore",
//         rating: 5,
//         user: user,
//         badges: ["New"],
//     },
//     {
//         id: 5,
//         slug: "honda-civic-1.8l-i-vtec",
//         name: "Honda Civic 1.8L i-VTEC",
//         excerpt: "",
//         description: "",
//         make: "Honda",
//         model: "Civic",
//         version: "1.8 i-VTEC",
//         price: 3200000,
//         compareAtPrice: 3100000,
//         transaction: {
//             transactionType: "Cash",
//             flatPrice: 3200000,
//         },
//         tags: ["Honda"],
//         colors: ["red"],
//         transmission: _t.CVT,

//         partNumber: "2323",
//         stock: "in-stock",
//         compatibility: "all",
//         type,
//         attributes: [],
//         options: [],

//         year: new Date(Date.parse("11/03/2021")),
//         mileage: 0,
//         assembly: "Local",
//         bodyType: bodyTypes[0],
//         images: ["honda-civic-1.8l-i-vtec.png"],
//         engine: _e.PETROL,
//         engineCapacity: 1800,
//         postedDate: new Date(Date.parse("11/03/2021")),
//         province: "Punjab",
//         city: "Lahore",
//         registrationCity: "Lahore",
//         rating: 5,
//         user: user,
//         badges: ["New"],
//     },
//     {
//         id: 6,
//         slug: "honda-civic-1.8l-i-vtec",
//         name: "Honda Civic 1.8L i-VTEC",
//         excerpt: "",
//         description: "",
//         make: "Honda",
//         model: "Civic",
//         version: "1.8 i-VTEC",
//         price: 3200000,
//         compareAtPrice: 3100000,
//         transaction: {
//             transactionType: "Cash",
//             flatPrice: 3200000,
//         },
//         tags: ["Honda"],
//         colors: ["red"],
//         transmission: _t.CVT,

//         partNumber: "2323",
//         stock: "in-stock",
//         compatibility: "all",
//         type,
//         attributes: [],
//         options: [],

//         year: new Date(Date.parse("11/03/2021")),
//         mileage: 0,
//         assembly: "Local",
//         bodyType: bodyTypes[0],
//         images: ["honda-civic-1.8l-i-vtec.png"],
//         engine: _e.PETROL,
//         engineCapacity: 1800,
//         postedDate: new Date(Date.parse("11/03/2021")),
//         province: "Punjab",
//         city: "Lahore",
//         registrationCity: "Lahore",
//         rating: 5,
//         user: user,
//         badges: ["New"],
//     },
//     {
//         id: 7,
//         slug: "honda-civic-1.8l-i-vtec",
//         name: "Honda Civic 1.8L i-VTEC",
//         excerpt: "",
//         description: "",
//         make: "Honda",
//         model: "Civic",
//         version: "1.8 i-VTEC",
//         price: 3200000,
//         compareAtPrice: 3100000,
//         transaction: {
//             transactionType: "Cash",
//             flatPrice: 3200000,
//         },
//         tags: ["Honda"],
//         colors: ["red"],
//         transmission: _t.CVT,

//         partNumber: "2323",
//         stock: "in-stock",
//         compatibility: "all",
//         type,
//         attributes: [],
//         options: [],

//         year: new Date(Date.parse("11/03/2021")),
//         mileage: 0,
//         assembly: "Local",
//         bodyType: bodyTypes[0],
//         images: ["honda-civic-1.8l-i-vtec.png"],
//         engine: _e.PETROL,
//         engineCapacity: 1800,
//         postedDate: new Date(Date.parse("11/03/2021")),
//         province: "Punjab",
//         city: "Lahore",
//         registrationCity: "Lahore",
//         rating: 5,
//         user: user,
//         badges: ["New"],
//     },
// ];

export {}